### ISSUE TITLE
Implement + document data directory mounting in the docker container!

### ISSUE THREAD

**Issue by MadcowD** [AIcrowd/neurips2019_minerl_challenge_starter_kit#10]
We should document how the data directory feature works.

**Comment by MadcowD** [comment]
We should also automatically mount the data directory according the users local MIENRL_DATA_DIR (for local evaluations)

**Comment by skbly7** [comment]
Hi, the documentation on data directory is added, we have created disk image of dataset as well. It will start to auto-mounted in online submission once we move on to Azure Kubernetes. (just to prevent double effort in adding k8s spec compatible to GKE currently and then Azure)
