### ISSUE TITLE
Documentation on local evaluation

### ISSUE THREAD

**Issue by MadcowD** [AIcrowd/neurips2019_minerl_challenge_starter_kit#2]
It doesn't look like there is any documentation on local evaluation

**Comment by spMohanty** [comment]
@skbly7 : Can you have a look at that ? 
Not sure if we should expose the subcontractor image thats used by the evaluator, or if we should simply have a block of instructions for launching the instance manager locally ?

**Comment by skbly7** [comment]
I have exposed `parser.py` used internally in subcontractor to make this possible. The current version of `parser.py` assumed there will be only one instance running in evaluation phase, which I believe will be true.

The instructions to evaluate locally is added here: https://github.com/AIcrowd/neurips2019_minerl_challenge_starter_kit#local-evaluation
