### ISSUE TITLE
Wrong environment used.

### ISSUE THREAD

**Issue by MadcowD** [AIcrowd/neurips2019_minerl_challenge_starter_kit#6]
The competitors should only be able to submit for evaluation on `MineRLObtainDiamond-v0`.

 Can we prevent any other environment being used (i.e. a fail their submission)?

**Comment by spMohanty** [comment]
@MadcowD : This is something we will have to handle at the instance manager level. Infact, I think we can pass the name of the env variable as an env variable.

**Comment by skbly7** [comment]
Thanks for pointing this out. The environment has been updated to `MineRLObtainDiamond-v0` everywhere now.

Regarding the automatic failure, the best way currently to know environment name in remote instance manager container is via `status.json` generated in performance directory. I have make necessary changes for failing as soon as `status.json` is generated i.e. after environment starts. 

If we can start dumping the incoming requests in remote instance manager code before generating the the environment, it can be done more preemptively.

Let us know if current solution is fine for time being.

**Comment by skbly7** [comment]
We are preventing usage of any random environment name by the env variable `MINERL_GYM_ENV`
