### ISSUE TITLE
Add train and evaluation sections to agent.py and improve docs on how submission will work

### ISSUE THREAD

**Issue by MadcowD** [AIcrowd/neurips2019_minerl_challenge_starter_kit#9]
To make it clear the competitors that there will be two different entry points/phases we should  have a train.py & a test.py  and specifically explain how round 1 will work (e.g. 
 - we will only use test.py, 
 - you are expected to train your agents using the **training phase docker container**
  - this training phase docker container will kill your process when the max number of samples is reached (8,000,000). **You need to ensure that your submission is trained in under this many samples and within a 4 day period on the hardware specified by the competition, because in phase 2 we will be doing this evaluation and asserting that your scores match!**
  - you are expected to **output the trained models to a mount called /train** 
  - we will then evaluate the model saved in the repo on the AICrowd servers using the entry-point test.py).

**Comment by skbly7** [comment]
I have added the newer entry points along with differences b/w round 1 and round 2. 

Currently, the `train.py` is getting `MINERL_TRAINING_MAX_SAMPLES` and `MINERL_TRAINING_TIMEOUT` variables, so the participants can consider those. BUT it isn't being enforced right now. 

What will be proper way to know #samples used?

**Comment by skbly7** [comment]
The users now have access to complete `performance` folder while running test phase locally/azure. The same has been shared by inline documentation in `train.py`.

They can initialise parser object like: https://github.com/AIcrowd/neurips2019_minerl_challenge_starter_kit/blob/master/train.py#L31

And check current state by doing `update_information` function. https://github.com/AIcrowd/neurips2019_minerl_challenge_starter_kit/blob/master/train.py#L75

The information provided is following struct: https://github.com/AIcrowd/neurips2019_minerl_challenge_starter_kit/blob/master/utility/parser.py#L64
